# Basics which should be included in all devices

# TODO if no client connects to the api after 15m the device reboots ?
api:
  #password: !secret api_password
  #encryption:
  #  key: !secret api_encryption_key

mqtt:
  broker: labgrid-exporter-0001
  reboot_timeout: 0s
  # TODO username, password & encryption
  #username: livingroom
  #password: !secret mqtt_password

  # TODO: Hack for labgrid Tasmota compatibility; see https://github.com/labgrid-project/labgrid/pull/918
  birth_message:
    topic:  ${name}/status
    payload: Online
  will_message:
    topic: ${name}/status
    payload: Offline

logger:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret wifi_ap_password
captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
