# Basics which should be included in all devices

api:
  reboot_timeout: 0s
  #password: !secret api_password
  #encryption:
  #  key: !secret api_encryption_key

logger:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  output_power: 10dB
  ap:
    password: !secret wifi_ap_password
captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
