# Basics which should be included in all devices

api:
  reboot_timeout: 0s
  #password: !secret api_password
  #encryption:
  #  key: !secret api_encryption_key

logger:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
  # Highest priority network is chosen first; e.g backup SSID is first.
  #
  # WARNING: each failed connection reduces the priority of that SSID by 1
  # before retrying the next highest priority - this can take a while if
  # priorities are high - each failed connection can take ~1s.
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 1000
  - ssid: !secret wifi_backup_ssid
    password: !secret wifi_backup_password
    priority: 1010

  # TODO use substitutions
  #power_save_mode: light
  #power_save_mode: ${power_save_mode}
  power_save_mode: none
  #output_power: 10dB
  #output_power: ${output_power}
  output_power: 20dB
  ap:
    # captive portal password
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
