# Basics which should be included in all devices

api:
  reboot_timeout: 0s
  #password: !secret api_password
  #encryption:
  #  key: !secret api_encryption_key

logger:

ota:
  password: !secret ota_password

wifi:
  networks:
  # Highest priority network is chosen first
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 1000
  - ssid: !secret wifi_backup_ssid
    password: !secret wifi_backup_password
    priority: 1000000

  # TODO use substitutions
  #power_save_mode: light
  #power_save_mode: ${power_save_mode}
  power_save_mode: none
  #output_power: 10dB
  #output_power: ${output_power}
  output_power: 20dB
  ap:
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
