# From https://devices.esphome.io/devices/M5Stack-M5StickC-PLUS

esphome:
  name: ${name}
  comment: ${comment}
  platform: ESP32
  board: m5stick-c
  platformio_options:
    upload_speed: 115200

wifi:
  networks:
  # Highest priority network is chosen first
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 1000
  - ssid: !secret wifi_backup_ssid
    password: !secret wifi_backup_password
    priority: 1000000

  ap:
    ssid: $comment Fallback Hotspot
    password: !secret wifi_password

captive_portal:

logger:

api:

ota:

external_components:
  - source: github://martydingo/esphome-axp192
    components: [axp192]

# AXP192 power management - must be present to initialize TFT power on
sensor:
  - platform: axp192
    model: M5STICKC
    address: 0x34
    i2c_id: bus_a
    update_interval: 60s
    battery_level:
      name: "${comment} Battery Level"

  # ENV II
  # see https://docs.m5stack.com/en/hat/hat_envII.R
  #
  # bmp280 - https://esphome.io/components/sensor/bmp280.html
  - platform: bmp280
    temperature:
      name: "${comment} BMP280 Temperature"
      #oversampling: 16x
    pressure:
      name: "${comment} BMP280 Pressure"
    i2c_id: ext_i2c_a
    address: 0x76
    update_interval: 10s
  # sht30 - https://esphome.io/components/sensor/sht3xd.html
  - platform: sht3xd
    temperature:
      name: "${comment} SHT30 Temperature"
    humidity:
      name: "${comment} SHT30 Humidity"
    i2c_id: ext_i2c_a
    address: 0x44
    update_interval: 10s


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${comment} Button A
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1

  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${comment} Button B
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1

light:
  - platform: monochromatic
    output:  builtin_led
    name: ${comment} Led
    id: led1

output:
  - platform: ledc
    pin: 10
    inverted: true
    id: builtin_led

# IR transmitter does not work
#remote_transmitter:
#  - pin:
#      number: GPIO9
#    carrier_duty_percent: 50%
#    id: internal

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
  # internal bus?
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True
  # 8-way header
  - id: ext_i2c_a
    sda: GPIO0
    scl: GPIO26
    scan: True

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 40

# 1.14 inch, 135*240 Colorful TFT LCD, ST7789v2
display:
  - platform: st7789v
    model: TTGO TDisplay 135x240
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 270
    lambda: |-
      it.print(10, 10, id(roboto), "M5Stick");
      it.print(10, 40, id(roboto), "${name}");
      it.print(10, 80, id(roboto), "${comment}");
