esphome:
  name: minimal

esp8266:
  board: esp01_1m

logger:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  manual_ip:
    # TODO: When uploading, change the static_ip to the old device address.
    static_ip: 192.168.1.113
    gateway: 192.168.1.254
    subnet: 255.255.255.0
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
