# Sonoff Basic PDU firmware
# https://esphome.io/devices/sonoff_s20.html

# To put into programming mode, press button while applying power.

<<: !include base.yaml
esphome:
  name: ${name}
  comment: ${comment}

esp8266:
  board: esp8285
# TODO set these:
#  restore_from_flash: true

binary_sensor:
  - name: "${comment} Power Button"
    id: ${id}_power_button
    platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: true
    on_click:
      - max_length: 1s
        then:
          switch.toggle: ${id}_relay

# light:
#   - name: "${comment} Status LED"
#     id: ${id}_status
#     platform: gpio
#     internal: True
#     pin:
#       number: GPIO13
#       inverted: True

# The relay switches on the red side of the LED when active.
switch:
  - platform: gpio
    name: "${comment} Relay"
    id: ${id}_relay
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF
