substitutions:
  name: pdu-s26-0003
  comment: PDU-S26-0003
  id: pdu_s26_0003

mqtt:
  broker: labgrid-exporter-0001
  reboot_timeout: 0s
  # TODO username, password & encryption
  #username: livingroom
  #password: !secret mqtt_password

<<: !include pdu-sonoff-s2x.yaml
