# Sonoff S20 PDU firmware
# https://esphome.io/devices/sonoff_s20.html
#
# The S26 uses the exact same pinout

<<: !include base.yaml
esphome:
  name: ${name}
  comment: ${comment}
  platform: ESP8266
  board: sonoff_s20

binary_sensor:
  - name: "${comment} Power Button"
    id: ${id}_power_button
    internal: true
    platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true

    # Hook up button press to toggle relay on/off
    on_press:
      then:
        - switch.toggle: ${id}_relay

switch:
  - name: "${comment} Relay"
    id: ${id}_relay
    platform: gpio
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - id: ${id}_led
    platform: gpio
    pin:
      number: GPIO13
      inverted: true

light:
  - name: "${comment} Status LED"
    id: ${id}_status
    internal: true
    platform: binary
    output: ${id}_led
