substitutions:
  name: pdu-boiler
  comment: pdu boiler
  id: pdu_boiler

<<: !include pdu-sonoff-basic.yaml

time:
  - platform: sntp
    timezone: "Europe/London"
    on_time:
      # Turn ON at 7:00 every day
      - hours: 7
        minutes: 0
        seconds: 0
        # days_of_week: MON-FRI
        then:
          - switch.turn_on: ${id}_relay

      # Turn OFF at 9:00 every day
      - hours: 9
        minutes: 0
        seconds: 0
        # days_of_week: MON-FRI
        then:
          - switch.turn_off: ${id}_relay
